function create_biological_motion_files_v1()
% Creates MATLAB files for the biological motion task.
% Includes individual and shared HOST/CLIENT conditions. No Psychtoolbox.

writeFile('make_bm_stimulus_table.m', make_stimulus_table_code());
writeFile('make_bm_trial_order.m', make_trial_order_code());
writeFile('run_biological_motion_individual.m', run_individual_code());
writeFile('run_biological_motion_shared_host.m', run_shared_host_code());
writeFile('run_biological_motion_shared_client.m', run_shared_client_code());
writeFile('bm_play_video_trial.m', play_video_code());
writeFile('bm_get_response.m', response_code());
writeFile('bm_wait_for_space.m', wait_space_code());
writeFile('bm_save_row.m', save_row_code());
writeFile('bm_compute_sdt.m', compute_sdt_code());
writeFile('bm_convert_stimuli_to_mp4.m', convert_code());

if ~exist('stimuli','dir'); mkdir('stimuli'); end
if ~exist('data','dir'); mkdir('data'); end

disp('Created biological motion task files.');
disp('Recommended: convert AVI to MP4 if needed, then run make_bm_stimulus_table and make_bm_trial_order.');
end

function writeFile(fname, txt)
fid = fopen(fname,'w');
if fid < 0; error('Could not create %s', fname); end
fprintf(fid,'%s',txt);
fclose(fid);
end

function txt = make_stimulus_table_code()
txt = [
"function stimTable = make_bm_stimulus_table(stimDir)" newline ...
"if nargin < 1 || isempty(stimDir)" newline ...
"    if exist(fullfile(pwd,'stimuli_mp4'),'dir')" newline ...
"        stimDir = fullfile(pwd,'stimuli_mp4');" newline ...
"    else" newline ...
"        stimDir = fullfile(pwd,'stimuli');" newline ...
"    end" newline ...
"end" newline ...
"if ~exist(stimDir,'dir'); error('Stimulus folder not found: %s', stimDir); end" newline ...
"files = [dir(fullfile(stimDir,'*.mp4')); dir(fullfile(stimDir,'*.avi'))];" newline ...
"if isempty(files); error('No MP4 or AVI files found in %s', stimDir); end" newline ...
"n = numel(files);" newline ...
"filename = strings(n,1); fullpath = strings(n,1); signalLabel = strings(n,1);" newline ...
"signalPresent = zeros(n,1); noise = zeros(n,1); direction = strings(n,1); position = zeros(n,1);" newline ...
"for i = 1:n" newline ...
"    fname = files(i).name;" newline ...
"    tok = regexp(fname, '^([SU])(12|24|48|96|192)([LR])(-?20|-?10|0)\.(avi|mp4)$', 'tokens', 'once');" newline ...
"    if isempty(tok); error('Filename does not match expected format: %s', fname); end" newline ...
"    filename(i) = string(fname); fullpath(i) = string(fullfile(stimDir,fname));" newline ...
"    noise(i) = str2double(tok{2}); direction(i) = string(tok{3}); position(i) = str2double(tok{4});" newline ...
"    if strcmp(tok{1},'U'); signalLabel(i) = 'walker'; signalPresent(i) = 1;" newline ...
"    else; signalLabel(i) = 'scrambled'; signalPresent(i) = 0; end" newline ...
"end" newline ...
"stimTable = table(filename,fullpath,signalLabel,signalPresent,noise,direction,position);" newline ...
"stimTable = sortrows(stimTable, {'signalLabel','noise','direction','position'});" newline ...
"writetable(stimTable,'stimuli.csv');" newline ...
"disp('Saved stimuli.csv');" newline ...
"disp(['Stimulus folder: ' stimDir]);" newline ...
"disp(['Number of stimuli found: ' num2str(height(stimTable))]);" newline ...
"nMain = sum(ismember(stimTable.noise,[24 48 96 192]));" newline ...
"if nMain ~= 80; warning('Expected 80 main-task stimuli, found %d.', nMain); end" newline ...
"end" newline ...
];
end

function txt = make_trial_order_code()
txt = [
"function trialTable = make_bm_trial_order(stimCsv,repetitions)" newline ...
"if nargin < 1 || isempty(stimCsv); stimCsv = 'stimuli.csv'; end" newline ...
"if nargin < 2 || isempty(repetitions); repetitions = 2; end" newline ...
"if ~exist(stimCsv,'file'); error('stimuli.csv not found. Run make_bm_stimulus_table first.'); end" newline ...
"stimTable = readtable(stimCsv,'TextType','string');" newline ...
"stimTable = stimTable(ismember(stimTable.noise,[24 48 96 192]),:);" newline ...
"if height(stimTable) ~= 80; warning('Expected 80 main stimuli, found %d. Continuing anyway.', height(stimTable)); end" newline ...
"trialTable = repmat(stimTable,repetitions,1);" newline ...
"trialTable.repetition = repelem((1:repetitions)',height(stimTable));" newline ...
"rng(20260607,'twister');" newline ...
"trialTable = trialTable(randperm(height(trialTable)),:);" newline ...
"trialTable.trial = (1:height(trialTable))';" newline ...
"trialTable = movevars(trialTable,'trial','Before',1);" newline ...
"save('bm_trial_order.mat','trialTable');" newline ...
"writetable(trialTable,'bm_trial_order.csv');" newline ...
"disp('Saved bm_trial_order.mat and bm_trial_order.csv');" newline ...
"end" newline ...
];
end

function txt = run_individual_code()
txt = [
"function run_biological_motion_individual(participantID)" newline ...
"if nargin < 1 || isempty(participantID); participantID = input('Participant ID: ','s'); end" newline ...
"prepareBMFiles(); load('bm_trial_order.mat','trialTable');" newline ...
"dataDir = fullfile(pwd,'data'); if ~exist(dataDir,'dir'); mkdir(dataDir); end" newline ...
"outfile = fullfile(dataDir,[participantID '_biological_motion_individual.csv']);" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off','Name','Biological Motion - Individual');" newline ...
"set(fig,'WindowState','maximized'); drawnow;" newline ...
"try" newline ...
"    showInstructions(fig,'individual'); runPractice(fig);" newline ...
"    for t = 1:height(trialTable)" newline ...
"        thisTrial = trialTable(t,:);" newline ...
"        showFixation(fig,0.5); bm_play_video_trial(fig,char(thisTrial.fullpath));" newline ...
"        [response,rt] = bm_get_response(fig);" newline ...
"        row = makeTrialRow(participantID,'individual',t,thisTrial,response,rt,'',datetime('now'));" newline ...
"        bm_save_row(outfile,row); showBlank(fig,0.3 + rand()*0.2);" newline ...
"    end" newline ...
"    showEnd(fig);" newline ...
"catch ME" newline ...
"    if isvalid(fig); close(fig); end; rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
common_local_code() ...
];
end

function txt = run_shared_host_code()
txt = [
"function run_biological_motion_shared_host(dyadID,participantID,port)" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID: ','s'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_A']; end" newline ...
"if nargin < 3 || isempty(port); port = 50000; end" newline ...
"prepareBMFiles(); load('bm_trial_order.mat','trialTable');" newline ...
"dataDir = fullfile(pwd,'data'); if ~exist(dataDir,'dir'); mkdir(dataDir); end" newline ...
"localFile = fullfile(dataDir,[participantID '_biological_motion_shared.csv']);" newline ...
"syncFile = fullfile(dataDir,[dyadID '_biological_motion_shared_sync.csv']);" newline ...
"disp(['Starting TCP server on port ' num2str(port)]);" newline ...
"srv = tcpserver('0.0.0.0',port,'Timeout',60); configureTerminator(srv,'LF');" newline ...
"disp('Waiting for client connection...'); while srv.Connected == 0; pause(0.1); end; disp('Client connected.');" newline ...
"writeline(srv,'HELLO_FROM_HOST');" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off','Name','Biological Motion - Shared Host');" newline ...
"set(fig,'WindowState','maximized'); drawnow;" newline ...
"try" newline ...
"    showInstructions(fig,'shared'); runPractice(fig); writeline(srv,'HOST_READY_FOR_MAIN');" newline ...
"    for t = 1:height(trialTable)" newline ...
"        thisTrial = trialTable(t,:);" newline ...
"        showSharedWaiting(fig,t,height(trialTable));" newline ...
"        triggeredBy = waitForSharedStartHost(fig,srv);" newline ...
"        trialStartTime = datetime('now');" newline ...
"        writeline(srv,sprintf('START|%d|%s',t,triggeredBy));" newline ...
"        showFixation(fig,0.5); bm_play_video_trial(fig,char(thisTrial.fullpath));" newline ...
"        [response,rt] = bm_get_response(fig); localDoneTime = datetime('now');" newline ...
"        writeline(srv,sprintf('DONE|%d|HOST',t));" newline ...
"        waitForClientDone(srv,t); bothDoneTime = datetime('now');" newline ...
"        iti = 0.3 + rand()*0.2; writeline(srv,sprintf('ITI|%.3f',iti));" newline ...
"        row = makeTrialRow(participantID,'shared',t,thisTrial,response,rt,triggeredBy,localDoneTime);" newline ...
"        bm_save_row(localFile,row);" newline ...
"        syncRow = table(string(dyadID),t,thisTrial.filename,thisTrial.signalLabel,thisTrial.signalPresent,thisTrial.noise,thisTrial.direction,thisTrial.position,string(triggeredBy),trialStartTime,bothDoneTime,iti, ..." newline ...
"            'VariableNames',{'dyadID','trial','filename','signalLabel','signalPresent','noise','direction','position','triggeredBy','trialStartTime','bothDoneTime','ITI'});" newline ...
"        bm_save_row(syncFile,syncRow); showBlank(fig,iti);" newline ...
"    end" newline ...
"    writeline(srv,'FINISHED'); showEnd(fig);" newline ...
"catch ME" newline ...
"    try; writeline(srv,'ABORT'); catch; end" newline ...
"    if isvalid(fig); close(fig); end; rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
"function triggeredBy = waitForSharedStartHost(fig,srv)" newline ...
"triggeredBy = ''; abortTask = false; set(fig,'KeyPressFcn',@keyHandler);" newline ...
"while isempty(triggeredBy)" newline ...
"    drawnow; if abortTask; error('Experiment aborted by HOST with ESC.'); end" newline ...
"    while srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg,'SPACE'); triggeredBy = 'CLIENT'; return; end" newline ...
"        if startsWith(msg,'ABORT'); error('Experiment aborted by CLIENT.'); end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~,event)" newline ...
"        switch event.Key; case 'space'; triggeredBy = 'HOST'; case 'escape'; abortTask = true; end" newline ...
"    end" newline ...
"end" newline ...
"function waitForClientDone(srv,trialNum)" newline ...
"while true" newline ...
"    drawnow;" newline ...
"    if srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg,sprintf('DONE|%d|CLIENT',trialNum)); return; end" newline ...
"        if startsWith(msg,'ABORT'); error('Experiment aborted by CLIENT.'); end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"end" newline ...
common_local_code() ...
];
end

function txt = run_shared_client_code()
txt = [
"function run_biological_motion_shared_client(dyadID,participantID,hostIP,port)" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID: ','s'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_B']; end" newline ...
"if nargin < 3 || isempty(hostIP); hostIP = input('Host IP address: ','s'); end" newline ...
"if nargin < 4 || isempty(port); port = 50000; end" newline ...
"prepareBMFiles(); load('bm_trial_order.mat','trialTable');" newline ...
"dataDir = fullfile(pwd,'data'); if ~exist(dataDir,'dir'); mkdir(dataDir); end" newline ...
"localFile = fullfile(dataDir,[participantID '_biological_motion_shared.csv']);" newline ...
"disp(['Connecting to host ' hostIP ':' num2str(port)]);" newline ...
"cli = tcpclient(hostIP,port,'Timeout',60); configureTerminator(cli,'LF'); pause(0.5);" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off','Name','Biological Motion - Shared Client');" newline ...
"set(fig,'WindowState','maximized'); drawnow;" newline ...
"try" newline ...
"    showInstructions(fig,'shared'); runPractice(fig); waitForHostReady(cli);" newline ...
"    for t = 1:height(trialTable)" newline ...
"        thisTrial = trialTable(t,:); showSharedWaiting(fig,t,height(trialTable));" newline ...
"        [trialNum,triggeredBy] = waitForSharedStartClient(fig,cli);" newline ...
"        if trialNum ~= t; error('Trial mismatch: expected %d, got %d',t,trialNum); end" newline ...
"        showFixation(fig,0.5); bm_play_video_trial(fig,char(thisTrial.fullpath));" newline ...
"        [response,rt] = bm_get_response(fig); localDoneTime = datetime('now');" newline ...
"        writeline(cli,sprintf('DONE|%d|CLIENT',t));" newline ...
"        iti = waitForITIorAbort(cli);" newline ...
"        row = makeTrialRow(participantID,'shared',t,thisTrial,response,rt,triggeredBy,localDoneTime);" newline ...
"        bm_save_row(localFile,row); showBlank(fig,iti);" newline ...
"    end" newline ...
"    showEnd(fig);" newline ...
"catch ME" newline ...
"    try; writeline(cli,'ABORT'); catch; end" newline ...
"    if isvalid(fig); close(fig); end; rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
"function waitForHostReady(cli)" newline ...
"while true" newline ...
"    drawnow;" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg,'HOST_READY_FOR_MAIN'); return; end" newline ...
"        if startsWith(msg,'ABORT'); error('Experiment aborted by HOST.'); end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"end" newline ...
"function [trialNum,triggeredBy] = waitForSharedStartClient(fig,cli)" newline ...
"trialNum = NaN; triggeredBy = ''; spaceAlreadySent = false; abortTask = false; set(fig,'KeyPressFcn',@keyHandler);" newline ...
"while isnan(trialNum)" newline ...
"    drawnow; if abortTask; writeline(cli,'ABORT'); error('Experiment aborted by CLIENT with ESC.'); end" newline ...
"    while cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg,'START'); parts = split(msg,'|'); trialNum = str2double(parts{2}); triggeredBy = parts{3}; return; end" newline ...
"        if startsWith(msg,'ABORT'); error('Experiment aborted by HOST.'); end" newline ...
"        if startsWith(msg,'FINISHED'); error('Host finished unexpectedly.'); end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~,event)" newline ...
"        switch event.Key" newline ...
"            case 'space'" newline ...
"                if ~spaceAlreadySent; writeline(cli,'SPACE|CLIENT'); spaceAlreadySent = true; end" newline ...
"            case 'escape'; abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"function iti = waitForITIorAbort(cli)" newline ...
"iti = NaN;" newline ...
"while isnan(iti)" newline ...
"    drawnow;" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg,'ITI'); parts = split(msg,'|'); iti = str2double(parts{2}); return; end" newline ...
"        if startsWith(msg,'ABORT'); error('Experiment aborted by HOST.'); end" newline ...
"        if startsWith(msg,'FINISHED'); iti = 0; return; end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"end" newline ...
common_local_code() ...
];
end

function txt = common_local_code()
txt = [
"function prepareBMFiles()" newline ...
"if ~exist('stimuli.csv','file'); make_bm_stimulus_table(); end" newline ...
"if ~exist('bm_trial_order.mat','file'); make_bm_trial_order(); end" newline ...
"end" newline ...
"function showInstructions(fig,modeLabel)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.82,'Biological Motion Detection Task','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized','Interpreter','none');" newline ...
"if strcmp(modeLabel,'shared')" newline ...
"    extra = {'In this condition, you and your partner will see the same animations.','Please respond privately. Do not discuss your response.',''};" newline ...
"else; extra = {}; end" newline ...
"instructions = [{'You will see short animations made of moving dots.'},{''},{'Your task is to decide whether you saw a human walker.'},{''},{'Press Y if you saw a walker.'},{'Press N if you did not see a walker.'},{''},extra,{'Please respond even if you are not completely sure.'},{''},{'Press SPACE to start practice.'}];" newline ...
"text(0.5,0.45,instructions,'Color','w','HorizontalAlignment','center','FontSize',20,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; bm_wait_for_space(fig);" newline ...
"end" newline ...
"function runPractice(fig)" newline ...
"stimTable = readtable('stimuli.csv','TextType','string');" newline ...
"practicePool = stimTable(ismember(stimTable.noise,[12 24]),:);" newline ...
"if height(practicePool) < 10; practicePool = stimTable; end" newline ...
"rng(20260608,'twister'); practicePool = practicePool(randperm(height(practicePool)),:);" newline ...
"practiceTable = practicePool(1:min(10,height(practicePool)),:);" newline ...
"for p = 1:height(practiceTable)" newline ...
"    showFixation(fig,0.5); bm_play_video_trial(fig,char(practiceTable.fullpath(p)));" newline ...
"    [response,~] = bm_get_response(fig);" newline ...
"    correct = double(strcmp(response,'yes')) == practiceTable.signalPresent(p);" newline ...
"    clf(fig); set(fig,'Color','k'); if correct; msg = 'Correct'; else; msg = 'Incorrect'; end" newline ...
"    text(0.5,0.5,msg,'Color','w','HorizontalAlignment','center','FontSize',32,'Units','normalized','Interpreter','none');" newline ...
"    axis off; drawnow; pause(0.8);" newline ...
"end" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,{'Practice finished.','','Press SPACE to start the main task.'},'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; bm_wait_for_space(fig);" newline ...
"end" newline ...
"function showSharedWaiting(fig,t,nTrials)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,sprintf(['Trial %d of %d\n\nYou and your partner will see the same animation.\nRespond privately.\n\nAfter both have responded, either participant may press SPACE to start.'],t,nTrials),'Color','w','HorizontalAlignment','center','FontSize',22,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow;" newline ...
"end" newline ...
"function showFixation(fig,dur)" newline ...
"clf(fig); set(fig,'Color','k'); text(0.5,0.5,'+','Color','w','HorizontalAlignment','center','FontSize',40,'Units','normalized','Interpreter','none'); axis off; drawnow; pause(dur);" newline ...
"end" newline ...
"function showBlank(fig,dur)" newline ...
"clf(fig); set(fig,'Color','k'); axis off; drawnow; pause(dur);" newline ...
"end" newline ...
"function showEnd(fig)" newline ...
"clf(fig); set(fig,'Color','k'); text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized','Interpreter','none'); axis off; drawnow;" newline ...
"end" newline ...
"function row = makeTrialRow(participantID,conditionLabel,t,thisTrial,response,rt,triggeredBy,timestamp)" newline ...
"signalPresent = thisTrial.signalPresent; responseWalker = double(strcmp(response,'yes')); correct = responseWalker == signalPresent;" newline ...
"hit = signalPresent == 1 && responseWalker == 1; falseAlarm = signalPresent == 0 && responseWalker == 1; miss = signalPresent == 1 && responseWalker == 0; correctRejection = signalPresent == 0 && responseWalker == 0;" newline ...
"row = table(string(participantID),string(conditionLabel),t,thisTrial.filename,thisTrial.signalLabel,signalPresent,string(response),responseWalker,correct,hit,falseAlarm,miss,correctRejection,thisTrial.noise,thisTrial.direction,thisTrial.position,rt,string(triggeredBy),timestamp, ..." newline ...
"    'VariableNames',{'participantID','condition','trial','filename','signalLabel','signalPresent','response','responseWalker','correct','hit','falseAlarm','miss','correctRejection','noise','direction','position','RT','triggeredBy','timestamp'});" newline ...
"end" newline ...
];
end

function txt = play_video_code()
txt = [
"function bm_play_video_trial(fig,videoPath)" newline ...
"if ~exist(videoPath,'file'); error('Video file not found: %s',videoPath); end" newline ...
"try; vid = VideoReader(videoPath);" newline ...
"catch ME" newline ...
"    error(['Could not read video file:\n%s\n\nOriginal error:\n%s\n\nIf this is an AVI file with cvid/Cinepak codec, convert stimuli to MP4 first:\nbm_convert_stimuli_to_mp4\nmake_bm_stimulus_table\nmake_bm_trial_order'],videoPath,ME.message);" newline ...
"end" newline ...
"clf(fig); set(fig,'Color','k'); ax = axes('Parent',fig,'Color','k','Position',[0 0 1 1]); axis(ax,'off');" newline ...
"firstFrame = readFrame(vid); h = image(ax,firstFrame); axis(ax,'image'); axis(ax,'off'); drawnow;" newline ...
"frameDuration = 1 / vid.FrameRate;" newline ...
"while hasFrame(vid)" newline ...
"    tic; frame = readFrame(vid); set(h,'CData',frame); drawnow limitrate; pause(max(0,frameDuration - toc));" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = response_code()
txt = [
"function [response,rt] = bm_get_response(fig)" newline ...
"response = ''; rt = NaN; abortTask = false; responseTic = tic;" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.58,'Did you see a human walker?','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized','Interpreter','none');" newline ...
"text(0.5,0.43,'Y = Yes     N = No','Color','w','HorizontalAlignment','center','FontSize',26,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; set(fig,'KeyPressFcn',@keyHandler);" newline ...
"while isempty(response)" newline ...
"    drawnow; if abortTask; error('Experiment aborted with ESC.'); end; pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~,event)" newline ...
"        switch lower(event.Key); case 'y'; response = 'yes'; rt = toc(responseTic); case 'n'; response = 'no'; rt = toc(responseTic); case 'escape'; abortTask = true; end" newline ...
"    end" newline ...
"end" newline ...
];
end

function txt = wait_space_code()
txt = [
"function bm_wait_for_space(fig)" newline ...
"done = false; abortTask = false; set(fig,'KeyPressFcn',@keyHandler);" newline ...
"while ~done" newline ...
"    drawnow; if abortTask; error('Experiment aborted with ESC.'); end; pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~,event)" newline ...
"        switch event.Key; case 'space'; done = true; case 'escape'; abortTask = true; end" newline ...
"    end" newline ...
"end" newline ...
];
end

function txt = save_row_code()
txt = [
"function bm_save_row(outfile,row)" newline ...
"[folder,~,~] = fileparts(outfile); if ~isempty(folder) && ~exist(folder,'dir'); mkdir(folder); end" newline ...
"if exist(outfile,'file'); writetable(row,outfile,'WriteMode','append'); else; writetable(row,outfile); end" newline ...
"end" newline ...
];
end

function txt = compute_sdt_code()
txt = [
"function summary = bm_compute_sdt(dataFile)" newline ...
"if nargin < 1 || isempty(dataFile); [f,p] = uigetfile('*.csv','Select participant data file'); if isequal(f,0); return; end; dataFile = fullfile(p,f); end" newline ...
"T = readtable(dataFile,'TextType','string'); noiseLevels = unique(T.noise); rows = table(); overall = computeOne(T,'overall');" newline ...
"for i = 1:numel(noiseLevels); rows = [rows; computeOne(T(T.noise==noiseLevels(i),:),string(noiseLevels(i)))]; end %#ok<AGROW>" newline ...
"summary = [overall; rows]; [folder,name,~] = fileparts(dataFile); outFile = fullfile(folder,[name '_SDT_summary.csv']); writetable(summary,outFile); disp(summary); disp(['Saved SDT summary: ' outFile]);" newline ...
"end" newline ...
"function row = computeOne(T,noiseText)" newline ...
"signalTrials = sum(T.signalPresent==1); noiseTrials = sum(T.signalPresent==0); hits = sum(T.hit==1); falseAlarms = sum(T.falseAlarm==1); misses = sum(T.miss==1); correctRejections = sum(T.correctRejection==1);" newline ...
"hitRate = (hits + 0.5)/(signalTrials + 1); faRate = (falseAlarms + 0.5)/(noiseTrials + 1); zH = norminv(hitRate); zFA = norminv(faRate); dprime = zH - zFA; criterionC = -0.5*(zH + zFA); accuracy = mean(T.correct); meanRT = mean(T.RT,'omitnan');" newline ...
"row = table(string(noiseText),signalTrials,noiseTrials,hits,misses,falseAlarms,correctRejections,hitRate,faRate,dprime,criterionC,accuracy,meanRT,'VariableNames',{'noise','signalTrials','noiseTrials','hits','misses','falseAlarms','correctRejections','hitRate','falseAlarmRate','dprime','criterionC','accuracy','meanRT'});" newline ...
"end" newline ...
];
end

function txt = convert_code()
txt = [
"function bm_convert_stimuli_to_mp4(stimDir,outDir)" newline ...
"if nargin < 1 || isempty(stimDir); stimDir = fullfile(pwd,'stimuli'); end" newline ...
"if nargin < 2 || isempty(outDir); outDir = fullfile(pwd,'stimuli_mp4'); end" newline ...
"if ~exist(stimDir,'dir'); error('Stimulus folder not found: %s',stimDir); end" newline ...
"if ~exist(outDir,'dir'); mkdir(outDir); end" newline ...
"[status,~] = system('ffmpeg -version');" newline ...
"if status ~= 0; error('ffmpeg was not found. Install it first. On Windows: winget install -e --id Gyan.FFmpeg'); end" newline ...
"files = dir(fullfile(stimDir,'*.avi')); if isempty(files); error('No AVI files found in %s',stimDir); end" newline ...
"for i = 1:numel(files)" newline ...
"    inFile = fullfile(stimDir,files(i).name); [~,base,~] = fileparts(files(i).name); outFile = fullfile(outDir,[base '.mp4']);" newline ...
"    if exist(outFile,'file'); fprintf('Already exists: %s\n',outFile); continue; end" newline ...
"    cmd = sprintf('ffmpeg -y -i \"%s\" -c:v libx264 -pix_fmt yuv420p -an \"%s\"',inFile,outFile);" newline ...
"    fprintf('Converting %s\n',files(i).name); status = system(cmd); if status ~= 0; error('ffmpeg failed while converting %s',files(i).name); end" newline ...
"end" newline ...
"disp('Conversion finished. Regenerate stimuli.csv and bm_trial_order files.');" newline ...
"end" newline ...
];
end
