function create_biological_motion_files_v1()

writeFile('make_bm_stimulus_table.m', make_stimulus_table_code());
writeFile('make_bm_trial_order.m', make_trial_order_code());
writeFile('run_biological_motion_individual.m', run_individual_code());
writeFile('bm_play_video_trial.m', play_video_code());
writeFile('bm_get_response.m', response_code());
writeFile('bm_save_row.m', save_row_code());
writeFile('bm_compute_sdt.m', compute_sdt_code());
writeFile('bm_convert_stimuli_to_mp4.m', convert_code());

if ~exist('stimuli', 'dir'); mkdir('stimuli'); end
if ~exist('data', 'dir'); mkdir('data'); end

disp('Created biological motion task files.');
disp('If AVI files give codec errors, run: bm_convert_stimuli_to_mp4');
disp('Then run: make_bm_stimulus_table');
disp('Then run: make_bm_trial_order');
end

function writeFile(fname, txt)
fid = fopen(fname, 'w');
if fid < 0
    error('Could not create %s', fname);
end
fprintf(fid, '%s', txt);
fclose(fid);
end

function txt = make_stimulus_table_code()
txt = [
"function stimTable = make_bm_stimulus_table(stimDir)" newline ...
"% Creates stimuli.csv by parsing video filenames." newline ...
"% Uses stimuli_mp4 if available; otherwise uses stimuli." newline ...
"" newline ...
"if nargin < 1 || isempty(stimDir)" newline ...
"    if exist(fullfile(pwd,'stimuli_mp4'), 'dir')" newline ...
"        stimDir = fullfile(pwd, 'stimuli_mp4');" newline ...
"    else" newline ...
"        stimDir = fullfile(pwd, 'stimuli');" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"if ~exist(stimDir, 'dir')" newline ...
"    error('Stimulus folder not found: %s', stimDir);" newline ...
"end" newline ...
"" newline ...
"files = [dir(fullfile(stimDir, '*.mp4')); dir(fullfile(stimDir, '*.avi'))];" newline ...
"if isempty(files)" newline ...
"    error('No MP4 or AVI files found in %s', stimDir);" newline ...
"end" newline ...
"" newline ...
"filename = strings(numel(files),1);" newline ...
"fullpath = strings(numel(files),1);" newline ...
"signalLabel = strings(numel(files),1);" newline ...
"signalPresent = zeros(numel(files),1);" newline ...
"noise = zeros(numel(files),1);" newline ...
"direction = strings(numel(files),1);" newline ...
"position = zeros(numel(files),1);" newline ...
"" newline ...
"for i = 1:numel(files)" newline ...
"    fname = files(i).name;" newline ...
"    token = regexp(fname, '^([SU])(12|24|48|96|192)([LR])(-?20|-?10|0)\.(avi|mp4)$', 'tokens', 'once');" newline ...
"    if isempty(token)" newline ...
"        error('Filename does not match expected format: %s', fname);" newline ...
"    end" newline ...
"" newline ...
"    filename(i) = string(fname);" newline ...
"    fullpath(i) = string(fullfile(stimDir, fname));" newline ...
"    signalCode = token{1};" newline ...
"    noise(i) = str2double(token{2});" newline ...
"    direction(i) = string(token{3});" newline ...
"    position(i) = str2double(token{4});" newline ...
"" newline ...
"    if strcmp(signalCode, 'U')" newline ...
"        signalLabel(i) = 'walker';" newline ...
"        signalPresent(i) = 1;" newline ...
"    else" newline ...
"        signalLabel(i) = 'scrambled';" newline ...
"        signalPresent(i) = 0;" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"stimTable = table(filename, fullpath, signalLabel, signalPresent, noise, direction, position);" newline ...
"stimTable = sortrows(stimTable, {'signalLabel','noise','direction','position'});" newline ...
"writetable(stimTable, 'stimuli.csv');" newline ...
"disp('Saved stimuli.csv');" newline ...
"disp(['Stimulus folder: ' stimDir]);" newline ...
"disp(['Number of stimuli found: ' num2str(height(stimTable))]);" newline ...
"" newline ...
"mainRows = ismember(stimTable.noise, [24 48 96 192]);" newline ...
"nMain = sum(mainRows);" newline ...
"if nMain ~= 80" newline ...
"    warning('Expected 80 main-task stimuli with noise 24/48/96/192, but found %d.', nMain);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = make_trial_order_code()
txt = [
"function trialTable = make_bm_trial_order(stimCsv, repetitions)" newline ...
"if nargin < 1 || isempty(stimCsv); stimCsv = 'stimuli.csv'; end" newline ...
"if nargin < 2 || isempty(repetitions); repetitions = 2; end" newline ...
"" newline ...
"if ~exist(stimCsv, 'file')" newline ...
"    error('stimuli.csv not found. Run make_bm_stimulus_table first.');" newline ...
"end" newline ...
"" newline ...
"stimTable = readtable(stimCsv, 'TextType', 'string');" newline ...
"stimTable = stimTable(ismember(stimTable.noise, [24 48 96 192]), :);" newline ...
"" newline ...
"if height(stimTable) ~= 80" newline ...
"    warning('Expected 80 main stimuli, found %d. Continuing anyway.', height(stimTable));" newline ...
"end" newline ...
"" newline ...
"trialTable = repmat(stimTable, repetitions, 1);" newline ...
"trialTable.repetition = repelem((1:repetitions)', height(stimTable));" newline ...
"" newline ...
"rng(20260607, 'twister');" newline ...
"idx = randperm(height(trialTable));" newline ...
"trialTable = trialTable(idx, :);" newline ...
"trialTable.trial = (1:height(trialTable))';" newline ...
"trialTable = movevars(trialTable, 'trial', 'Before', 1);" newline ...
"" newline ...
"save('bm_trial_order.mat', 'trialTable');" newline ...
"writetable(trialTable, 'bm_trial_order.csv');" newline ...
"disp('Saved bm_trial_order.mat and bm_trial_order.csv');" newline ...
"end" newline ...
];
end

function txt = run_individual_code()
txt = [
"function run_biological_motion_individual(participantID)" newline ...
"if nargin < 1 || isempty(participantID)" newline ...
"    participantID = input('Participant ID, e.g. dyad001_A: ', 's');" newline ...
"end" newline ...
"" newline ...
"if ~exist('stimuli.csv', 'file'); make_bm_stimulus_table(); end" newline ...
"if ~exist('bm_trial_order.mat', 'file'); make_bm_trial_order(); end" newline ...
"load('bm_trial_order.mat', 'trialTable');" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir'); mkdir(dataDir); end" newline ...
"outfile = fullfile(dataDir, [participantID '_biological_motion_individual.csv']);" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Biological Motion Detection - Individual');" newline ...
"set(fig, 'WindowState', 'maximized'); drawnow;" newline ...
"" newline ...
"try" newline ...
"    showInstructions(fig);" newline ...
"    runPractice(fig);" newline ...
"" newline ...
"    for t = 1:height(trialTable)" newline ...
"        thisTrial = trialTable(t,:);" newline ...
"        showFixation(fig, 0.5);" newline ...
"        bm_play_video_trial(fig, thisTrial.fullpath{1});" newline ...
"        [response, rt] = bm_get_response(fig);" newline ...
"" newline ...
"        signalPresent = thisTrial.signalPresent;" newline ...
"        responseWalker = double(strcmp(response, 'yes'));" newline ...
"        correct = responseWalker == signalPresent;" newline ...
"        hit = signalPresent == 1 && responseWalker == 1;" newline ...
"        falseAlarm = signalPresent == 0 && responseWalker == 1;" newline ...
"        miss = signalPresent == 1 && responseWalker == 0;" newline ...
"        correctRejection = signalPresent == 0 && responseWalker == 0;" newline ...
"" newline ...
"        row = table(string(participantID), t, thisTrial.filename, thisTrial.signalLabel, ..." newline ...
"            signalPresent, string(response), responseWalker, correct, hit, falseAlarm, miss, ..." newline ...
"            correctRejection, thisTrial.noise, thisTrial.direction, thisTrial.position, rt, datetime('now'), ..." newline ...
"            'VariableNames', {'participantID','trial','filename','signalLabel','signalPresent', ..." newline ...
"            'response','responseWalker','correct','hit','falseAlarm','miss','correctRejection', ..." newline ...
"            'noise','direction','position','RT','timestamp'});" newline ...
"        bm_save_row(outfile, row);" newline ...
"        showBlank(fig, 0.3 + rand()*0.2);" newline ...
"    end" newline ...
"" newline ...
"    showEnd(fig);" newline ...
"catch ME" newline ...
"    if isvalid(fig); close(fig); end" newline ...
"    rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function showInstructions(fig)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.82,'Biological Motion Detection Task','Color','w','HorizontalAlignment','center', ..." newline ...
"    'FontSize',28,'Units','normalized','Interpreter','none');" newline ...
"instructions = {'You will see short animations made of moving dots.','', ..." newline ...
"    'Your task is to decide whether you saw a human walker.','', ..." newline ...
"    'Press Y if you saw a walker.','Press N if you did not see a walker.','', ..." newline ...
"    'Please respond even if you are not completely sure.','', ..." newline ...
"    'Press SPACE to start practice.'};" newline ...
"text(0.5,0.47,instructions,'Color','w','HorizontalAlignment','center', ..." newline ...
"    'FontSize',20,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; waitForSpaceOrEscape(fig);" newline ...
"end" newline ...
"" newline ...
"function runPractice(fig)" newline ...
"stimTable = readtable('stimuli.csv', 'TextType', 'string');" newline ...
"practicePool = stimTable(ismember(stimTable.noise, [12 24]), :);" newline ...
"if height(practicePool) < 10; practicePool = stimTable; end" newline ...
"rng(20260608, 'twister');" newline ...
"practicePool = practicePool(randperm(height(practicePool)), :);" newline ...
"practiceTable = practicePool(1:min(10,height(practicePool)), :);" newline ...
"" newline ...
"for p = 1:height(practiceTable)" newline ...
"    showFixation(fig, 0.5);" newline ...
"    bm_play_video_trial(fig, practiceTable.fullpath{p});" newline ...
"    [response, ~] = bm_get_response(fig);" newline ...
"    signalPresent = practiceTable.signalPresent(p);" newline ...
"    responseWalker = double(strcmp(response, 'yes'));" newline ...
"    correct = responseWalker == signalPresent;" newline ...
"    clf(fig); set(fig,'Color','k');" newline ...
"    if correct; msg = 'Correct'; else; msg = 'Incorrect'; end" newline ...
"    text(0.5,0.5,msg,'Color','w','HorizontalAlignment','center','FontSize',32, ..." newline ...
"        'Units','normalized','Interpreter','none');" newline ...
"    axis off; drawnow; pause(0.8);" newline ...
"end" newline ...
"" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,{'Practice finished.','','Press SPACE to start the main task.'}, ..." newline ...
"    'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; waitForSpaceOrEscape(fig);" newline ...
"end" newline ...
"" newline ...
"function showFixation(fig, dur)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,'+','Color','w','HorizontalAlignment','center','FontSize',40, ..." newline ...
"    'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow; pause(dur);" newline ...
"end" newline ...
"" newline ...
"function showBlank(fig, dur)" newline ...
"clf(fig); set(fig,'Color','k'); axis off; drawnow; pause(dur);" newline ...
"end" newline ...
"" newline ...
"function showEnd(fig)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28, ..." newline ...
"    'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow;" newline ...
"end" newline ...
"" newline ...
"function waitForSpaceOrEscape(fig)" newline ...
"done = false; abortTask = false;" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"while ~done" newline ...
"    drawnow;" newline ...
"    if abortTask; error('Experiment aborted with ESC.'); end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~, event)" newline ...
"        switch event.Key" newline ...
"            case 'space'; done = true;" newline ...
"            case 'escape'; abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
];
end

function txt = play_video_code()
txt = [
"function bm_play_video_trial(fig, videoPath)" newline ...
"if ~exist(videoPath, 'file'); error('Video file not found: %s', videoPath); end" newline ...
"try" newline ...
"    vid = VideoReader(videoPath);" newline ...
"catch ME" newline ...
"    error(['Could not read video file:\n%s\n\nOriginal error:\n%s\n\n' ..." newline ...
"        'If this is an AVI file with cvid/Cinepak codec, convert stimuli to MP4 first:\n' ..." newline ...
"        'bm_convert_stimuli_to_mp4\nmake_bm_stimulus_table\nmake_bm_trial_order'], videoPath, ME.message);" newline ...
"end" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"ax = axes('Parent',fig,'Color','k','Position',[0 0 1 1]); axis(ax,'off');" newline ...
"firstFrame = readFrame(vid);" newline ...
"h = image(ax, firstFrame); axis(ax,'image'); axis(ax,'off'); drawnow;" newline ...
"frameDuration = 1 / vid.FrameRate;" newline ...
"while hasFrame(vid)" newline ...
"    tic;" newline ...
"    frame = readFrame(vid);" newline ...
"    set(h, 'CData', frame);" newline ...
"    drawnow limitrate;" newline ...
"    pause(max(0, frameDuration - toc));" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = response_code()
txt = [
"function [response, rt] = bm_get_response(fig)" newline ...
"response = ''; rt = NaN; abortTask = false; responseTic = tic;" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.58,'Did you see a human walker?','Color','w','HorizontalAlignment','center', ..." newline ...
"    'FontSize',28,'Units','normalized','Interpreter','none');" newline ...
"text(0.5,0.43,'Y = Yes     N = No','Color','w','HorizontalAlignment','center', ..." newline ...
"    'FontSize',26,'Units','normalized','Interpreter','none');" newline ...
"axis off; drawnow;" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"while isempty(response)" newline ...
"    drawnow;" newline ...
"    if abortTask; error('Experiment aborted with ESC.'); end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"    function keyHandler(~, event)" newline ...
"        switch lower(event.Key)" newline ...
"            case 'y'; response = 'yes'; rt = toc(responseTic);" newline ...
"            case 'n'; response = 'no'; rt = toc(responseTic);" newline ...
"            case 'escape'; abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
];
end

function txt = save_row_code()
txt = [
"function bm_save_row(outfile, row)" newline ...
"[folder, ~, ~] = fileparts(outfile);" newline ...
"if ~isempty(folder) && ~exist(folder, 'dir'); mkdir(folder); end" newline ...
"if exist(outfile, 'file')" newline ...
"    writetable(row, outfile, 'WriteMode', 'append');" newline ...
"else" newline ...
"    writetable(row, outfile);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = compute_sdt_code()
txt = [
"function summary = bm_compute_sdt(dataFile)" newline ...
"if nargin < 1 || isempty(dataFile)" newline ...
"    [f,p] = uigetfile('*.csv','Select participant data file');" newline ...
"    if isequal(f,0); return; end" newline ...
"    dataFile = fullfile(p,f);" newline ...
"end" newline ...
"T = readtable(dataFile, 'TextType','string');" newline ...
"noiseLevels = unique(T.noise);" newline ...
"rows = table();" newline ...
"overall = computeOne(T, 'overall');" newline ...
"for i = 1:numel(noiseLevels)" newline ...
"    rows = [rows; computeOne(T(T.noise==noiseLevels(i),:), string(noiseLevels(i)))]; %#ok<AGROW>" newline ...
"end" newline ...
"summary = [overall; rows];" newline ...
"[folder,name,~] = fileparts(dataFile);" newline ...
"outFile = fullfile(folder, [name '_SDT_summary.csv']);" newline ...
"writetable(summary, outFile);" newline ...
"disp(summary);" newline ...
"disp(['Saved SDT summary: ' outFile]);" newline ...
"end" newline ...
"" newline ...
"function row = computeOne(T, noiseText)" newline ...
"signalTrials = sum(T.signalPresent == 1);" newline ...
"noiseTrials = sum(T.signalPresent == 0);" newline ...
"hits = sum(T.hit == 1);" newline ...
"falseAlarms = sum(T.falseAlarm == 1);" newline ...
"misses = sum(T.miss == 1);" newline ...
"correctRejections = sum(T.correctRejection == 1);" newline ...
"hitRate = (hits + 0.5) / (signalTrials + 1);" newline ...
"faRate = (falseAlarms + 0.5) / (noiseTrials + 1);" newline ...
"zH = norminv(hitRate);" newline ...
"zFA = norminv(faRate);" newline ...
"dprime = zH - zFA;" newline ...
"criterionC = -0.5 * (zH + zFA);" newline ...
"accuracy = mean(T.correct);" newline ...
"meanRT = mean(T.RT, 'omitnan');" newline ...
"row = table(string(noiseText), signalTrials, noiseTrials, hits, misses, falseAlarms, correctRejections, ..." newline ...
"    hitRate, faRate, dprime, criterionC, accuracy, meanRT, ..." newline ...
"    'VariableNames', {'noise','signalTrials','noiseTrials','hits','misses','falseAlarms', ..." newline ...
"    'correctRejections','hitRate','falseAlarmRate','dprime','criterionC','accuracy','meanRT'});" newline ...
"end" newline ...
];
end

function txt = convert_code()
txt = [
"function bm_convert_stimuli_to_mp4(stimDir, outDir)" newline ...
"% Converts AVI stimuli to MP4 using ffmpeg." newline ...
"% Requires ffmpeg to be installed and available from the system path." newline ...
"" newline ...
"if nargin < 1 || isempty(stimDir); stimDir = fullfile(pwd, 'stimuli'); end" newline ...
"if nargin < 2 || isempty(outDir); outDir = fullfile(pwd, 'stimuli_mp4'); end" newline ...
"if ~exist(stimDir, 'dir'); error('Stimulus folder not found: %s', stimDir); end" newline ...
"if ~exist(outDir, 'dir'); mkdir(outDir); end" newline ...
"" newline ...
"[status, ~] = system('ffmpeg -version');" newline ...
"if status ~= 0" newline ...
"    error(['ffmpeg was not found. Install ffmpeg first, then run this function again.\n' ..." newline ...
"        'On Windows, one option is: winget install Gyan.FFmpeg']);" newline ...
"end" newline ...
"" newline ...
"files = dir(fullfile(stimDir, '*.avi'));" newline ...
"if isempty(files); error('No AVI files found in %s', stimDir); end" newline ...
"" newline ...
"for i = 1:numel(files)" newline ...
"    inFile = fullfile(stimDir, files(i).name);" newline ...
"    [~, base, ~] = fileparts(files(i).name);" newline ...
"    outFile = fullfile(outDir, [base '.mp4']);" newline ...
"    if exist(outFile, 'file')" newline ...
"        fprintf('Already exists: %s\n', outFile);" newline ...
"        continue;" newline ...
"    end" newline ...
"    cmd = sprintf('ffmpeg -y -i ""%s"" -c:v libx264 -pix_fmt yuv420p -an ""%s""', inFile, outFile);" newline ...
"    fprintf('Converting %s\n', files(i).name);" newline ...
"    status = system(cmd);" newline ...
"    if status ~= 0" newline ...
"        error('ffmpeg failed while converting %s', files(i).name);" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"disp('Conversion finished.');" newline ...
"disp('Now run: make_bm_stimulus_table');" newline ...
"disp('Then run: make_bm_trial_order');" newline ...
"end" newline ...
];
end